/* header chdef - character definitions and functions */
#ifndef _RIDER_H_chdef
#define _RIDER_H_chdef 1
int ch_low (int );
int ch_upr (int );
int ch_mat (char *,int );
#define _end ('\0')
#define _eos ('\0')
#define _bell ('\a')
#define _tab ('\t')
#define _ff ('\f')
#define _eop ('\f')
#define _vt ('\v')
#define _nl ('\n')
#define _cr ('\r')
#define _esc ('\033')
#define _space (' ')
#define _exclam ('!')
#define _quotes ('\"')
#define _hash ('#')
#define _dollar ('$')
#define _perct ('%')
#define _amper ('&')
#define _apost ('\'')
#define _paren ('(')
#define paren_ (')')
#define _star ('*')
#define _plus ('+')
#define _comma (',')
#define _minus ('-')
#define _dot ('.')
#define _slash ('/')
#define _0 ('0')
#define _1 ('1')
#define _2 ('2')
#define _3 ('3')
#define _4 ('4')
#define _5 ('5')
#define _6 ('6')
#define _7 ('7')
#define _8 ('8')
#define _9 ('9')
#define _colon (':')
#define _semi (';')
#define _angle ('<')
#define _equal ('=')
#define angle_ ('>')
#define _qmark ('\?')
#define _at ('@')
#define _A ('A')
#define _Z ('Z')
#define _square ('[')
#define _back ('\\')
#define square_ (']')
#define _hat ('^')
#define _under ('_')
#define _tick ('`')
#define _a ('a')
#define _z ('z')
#define _curly ('{')
#define _bar ('|')
#define curly_ ('}')
#define _tilde ('~')
#endif
