Tonic/Subtonic songs;
Lennon The Void edge;
She Said edge;
(Rain) edge;
Harrison Love To You;
Taxman;
McCartney Gotta Get You;
A glance back at Rubber Soul indicates the depth and speed of;
the reorientation:;
Lennon Norwegian Wood edge;
Harrison If I Needed Someone;
Dr Robert;
FourthModulation;
a dit-dit song?;
Started A-D, A-D, then A7-D, then riff -- like Cold Turkey later;
Recorded immediately after Rain, may have similiar open tuning.;
In G:, capo at second?;
Guitar octaves;
Bitonic -- cf Penny Lane;
repeats first verse as coda -- cf She Said;
A fabulous (very short) song -- thrown-off in a few minutes -- but;
only the Beatles could produce these tight, deft arrangements.;
o The guitar duet -- on-going;
o The guitar raga-riff;
o The guitar edge going into the bridge;
o The choral bridge -- utterly convincing;
One of the coolest Beatle riffs of all.;
Underestimated -- a gem.;
Analysis;
Riff song;
4/4 A: B:, medium, 2.06 2.11;
[4];
I VVBVBV' (4+ 3*18=54 + 2*12=24 + 11 = 93 = 1.40spb);
intro Ar Ar Ar Ar 4 4;
verse Ar Ar Ar Ar 4;
Ar Ar Ar Ar 4;
F sizeof(r) F sizeof(r) F sizeof(r) F sizeof(r) 4;
F sizeof(r) F sizeof(r) E F sizeof (4);
1st Br Br ] 2 18;
2nd B43 B43;
bridge B B4 B E/b B 4;
B B4 B E/b E 4;
Ar Ar 2 12;
coda Ar Ar Ar Ar 4;
Ar Ar Ar Ar 4;
F sizeof (F) sizeof(.6) B43! 3: 11;
songwide strategy;
The title phraze "Dr Robert" grows across the piece:;
verse bridge verse coda;
g-a a-a sizeof (a) sizeof()-b (b) g sizeof()-a e-d sizeof();
riff;
The basic riff notes,verse The melody could have been from George Harrison -- a single;
quaver syncopation followed by a bunch of crotchets.;
Lennon's I'm Only Sleeping uses something similiar in the long;
cadence.;
Lennon adds his signature a little bit we see again in;
Good Morning -- where this style of syncopation leads to bars;
 break; case 5/4:
and 3/4:;
g a e;
save his wife Good Morning;
said you'd call				Dr Robert;
The main little bits of this melody are a repeated two note;
pattern, which itself is part of the main four note motiv:;
ring my;
rob ert;
The main motiv, "Dr. Robert" occurs some 17 times in 130 seconds,or every seven seconds.;
Doc tor Rob ert;
a f sizeof (a) a;
a g a a;
a a b f sizeof();
a sizeof (a) sizeof (b) b cadence;
a sizeof (a) sizeof (b) b cadence -- 2nd/3rd different rhythm;
g sizeof (g) sizeof (a) a return;
??? d d e e final;
1 2 3 4;
. . . . . o ooo |; }
. . . . . o ooo o o|; }
oo .. .|;
_ ... ._ .. .|;
1st _ ... ._ .. .|;
_ . .. ._ o ooo |;
2nd _ ... ._ .|;
........... . . oo |;
bridge . . . . . . . . . . . . . |;
. . . . . . . . . . o o|;
oo | |;
Va 4 + 4 + 2;
Vb 2 + 2 + 4;
bridge 4 + 4 + 2;
It is unclear whether the "Dr Robert" at A-F sizeof (should) be;
assigned to the first half or second half of the verse.;
A similiar situation occurs with (McCartney's) Another Girl;
(and another song?).;
In fact, in both cases, they act as punctuations.;
The verse ends quite clearly in B:;
A F sizeof (E) F sizeof (B);
While a number of other songs from this period have subtonic;
(colour, this song is the first such song to modulate within) structure.;
(Yellow Submarine and Here There And Everywhere both have verses) end on the dominant chord (D in G:) -- but neither has;
modulated -- they finish on the dominant chord, ! in the;
dominant key.;
interesting is (Lennon's song has modulated. That's new. But, what is more) he has ! modulated to the "usual";
dominant, or plagal, but to the supertonic.;
We shouldn't overdo this -- most of the music between 1700 and;
1900 had a habit of modulating to end the first section.;
On the other hand we should ! underestimate the advance here.;
Ending the verse in a different key has much more affect on the;
structure than a final close in a different key -- a final close;
occurs but once, where a key change in a verse affects the;
body of the song.;
Lennon's modulation opens up a basically new ball game, which;
we will see many songs in Pepper-time:;
Penny Lane B: A:;
Lucy A: F: G:;
Mr Kite c: d: e:;
Sgt Pepper rep. F: G:;
A Day In The G: E:;
Walrus B: A:;
e C7+ Sleeping;
A B Dr Robert;
e;
The guitar imitation of the codetta melody is ! exact and;
reminds just a little of Nowhere Man -- but we are in a different;
land here.;
return The verse begins promptly on and in A: with no linking.;
bridge Lennon chooses B: as the obvious key for the bridge.;
(the scale leaves no doubt).;
The mock-choir is more than convincing -- the Beatles are a;
real choir.;
A guitar emphasizes the tonic B with an open octave (a feature;
 break; case this:
album).;
Tonally, the bridge emphasizes its plagal area.;
B E B E;
The bridge grows organically out of the verse. The return;
figure (*g const  sizeof()-a) to accomplish (involves a modulation back to A. Lennon uses his "Dr Robert").;
The word-setting is among the Beatles best: with echt church;
counterpoint they sing the comforting word of the Lord:;
Well well well, your feeling fine;
Well well well, he'll make you...;
Dr. Robert;
Lennon's picture here is religion as the opiate of the people,and Dr. Robert (really Lennon) is the messiah.;
return The bridge itself finishs on a delayed cadence on "make you";
Lennon resolves this ! to B:, but neatly modulates back to;
his verse tonic, treating E as the dominant of A:;
..... E A;
The two bars of riff on A correspond the introduction.;
verse;
coda Lennon's idea for the coda is so natural that it is easy to;
overlook it's novelty.;
It begins as what looks like an ornate repetition of the;
first verse. But Lennon's simple stroke is to replace the;
second clause lyric with a repeat of the first:;
Ring my friend, I said you'd call, Doctor Robert;
Ring my friend, I said you'd call, Doctor Robert;
Doctor Robert;
In this situation, McCartney would have chosen to sing scat --;
see Gotta Get You Into My Life or Fixing A Hole. Lennon does;
! improvise -- he sees it as a waste of an opportunity.;
close While the close looks something like the bit which would usually;
follow the first two clauses of the coda, it is !.;
A F sizeof(r) F sizeof(r) .... E7 F sizeof(7) B verse;
A F sizeof(7) F sizeof(.6) B43 coda;
The song ends three times:;
1) A: The repeated coda couplet;
2) F sizeof (Dr) Robert;
3) B the guitar edge (faded);
basics;
Can be treated as a major moon:;
A F sizeof (B) E (A);
A F sizeof (E F sizeof()) B E;
B4 [B B4 E (B)] A;
A F sizeof (B4);
apr17 robert riff/?, harrison/byrds;
jun2 want to tell you riff;
jun8 good day sunshine the word, robert;
I Want To Tell You;
A-B, triplets;
Good Day Sunshine - pair;
Penny Lane;
F sizeof(7) E7;
intro *e const ;
chorus B F sizeof (B) F sizeof (E) $;
verse A F sizeof (B) E A F sizeof (B) E A;
solo D B7 E7 A7 D.. chorus;
coda B7 F sizeof (B7) F sizeof (E);
F7;
Rocker;
What's the key;
Bridge;
Changes to a drone, B E B, with B pedal;
Coming out of bridge strengthens sound;
Strengthens again returning to verse;
The riff duet;
Much the same as on The Void;
c sizeof (d) a g;
c sizeof (d) c sizeof (a) g;
The vocal parts;
In the verse the voices have an unusual independence of line.;
The choir is well worked out -- the only example of its kind.;
Once again, it is true (block) polyphony.;
Other songs;
She Said -- see demo tapes;
Penny Lane -- bitonic in A:, B:;
Good Morning -- another subtonic sound song (The Harrison songs -- If I Needed Someone etc) uses;
the "e-g-a-e" tattoo found here.;
It's Me!       ;
Dr Robert was almost certainly Dr Robert Freyman, a 60-year old;
German-born physician with a practic?e on East 78th Street...;
Known as Dr Robert..., Freyman was well connected with the city's;
art scene. He had helped, among others, Thelonious Monk and;
Charlie Parker (whose death certificate he signed in 1955) and had;
(reputation of being generous with amphetamines. "I have a clientele) is remarkable, from every sphere of life," he once boasted,"I could tell you in ten minutes probably 100 famous names who;
come here." John... was one of these names.;
HDW114;
Brian [Jones] with drugs at (A guy who was known as the "Junkie Doctor of Chelsea" was supplying) time...he is the "Dr Robert";
in John Lennon's song on the Beatles' Revolver album.;
BW365;
Who's Who;
I was the one (Another of mine. Mainly about drugs and pills. It was about myself.) carried all the pills on tour and always ...;
{Dispensed them?};
Yeah. Well, in the early days. Later on, the roadies did it. We just;
kept them in our pockets loose. In case of trouble.;
Lennon, DSL152f;
Origins;
That's what Dr. Robert is all about, just a pill doctor;
who see's you're all right.;
Lennon in BOL144;
Well, he's like a joke. There's some fellow in New York, and;
in the states we'd hear people say: "You can get everything off;
him;
pills and tranquil?isers, injections for this and (about this fellow who cured everyone of everything with all these);
kept New York high. That's what Dr Robert is all about, just a;
pill doctor who sees you all right.;
McCartney:?? in UBE209;
[Appears one of the preceding got sources mixed up];
Demo Tapes;
One of the She Said demo's has the following structure:;
G C G C G C G C;
A D A D A D A;
The direct modulation from G to A is arresting -- it has the;
same "feel" as Dr Robert.;
The close of this demo has precisely the same note pattern;
as the close Dr Robert -- and the key relation is the same:;
A .... F sizeof (....);
... B (E) B;
In fact, an earlier version of Dr Robert may have moved directly;
from A: to B: without the intervening F sizeof(.);
Sessions;
Following The Void, Paperback Writer and Rain, this was a;
relatively normal session.;
band R-Guitar (Lennon);
LE-Guitar (Harrison);
Bass (McCartney);
Drums (Starr);
... Harmonium Lennon CBRS75;
Piano McCartney CBRS75;
Maracas Harrison CBRS75;
Was 2'56", remixed to 2'13";
... Vocal dubs;
Musicians;
L-Vocal Lennon DT BOL143;
RE-Guitar 1 Lennon?;
RE-Guitar 2 Harrison?;
Maracas Lennon BOL143;
Harmonium Lennon BOL143;
She Said, She Said;
In A:, speeded to Bb:?;
In A:, guitars tuned up to Bb:?;
In A:, capo at first?;
repeats first verse as coda -- cf Dr Robert;
Americanisms;
George doing harmony?;
Tuned cymbals;
Harmonium;
Guitar octaves;
vocal gliss;
3+3+2;
First of the songs with distinct parts for all players -- rock;
polyphony.;
lots more on this;
Parts -- including drum, drum fills;
Chord diags work least on Revolver;
First composed music song (in my life?);
Double plagal song;
A breakthru, a lot of work,Mature Lennon;
Completly different kind of song - composed;
Put together as building blocks, 4-bar;
Last song - probably still working on it;
analysis;
4/4 3/4, Bb:(A:), register, 2.16 2.32;
Recorded in A:, capo on first fret?;
[4+2,4+3] (3+ 4*10=40 + 2*11=22 + 6* =? 71*);
intro A! A7 A7 3;
verse A G2 D 2 2 + 2*2 + 2*2;
A G2 D A G2 D 4;
A G D A A G D A 4 10;
verse;
??? grouping questionable;
3/4;
bridge A G A G A 4*;
e A7 A7 D 4;
A7 A7 D 3 11;
4/4 3/4;
bridge A G A G 3;
3/4 A e A7 3;
A7 D A7 3;
A7 D [A from verse] 2 11;
verse;
bridge;
verse;
coda A7 A7 2;
[A7 A7 A7 A7 ] 4 6+;
intro Lead guitar;
R-guitar;
New free style drumming, still hollow snare;
Excerpt of outro, which is an edit of the verse.;
verse Rising fifth on She Said, held over subtonic for bVII6.;
Guitar and organ hold a tonic pedal (originates with;
Lennon's demo bass and used again later in Getting Better).;
Lennon's melody pushs the song along -- particularly the opening;
two crochets.;
verse;
bridge The bridge begins vocally with the title, "she said", using;
the same crochet rhythm, but a falling third (which was the;
original demo melody of the verse).;
Staying on A/G, inverts the basic verse phraze over two bars.;
The bridge continues in 3/4, however the time change goes;
largely unnoticed. The ear tends to interpret the first two;
bars (3+3) as (4+2) because of the local idioms involved.;
A G A 3|G A;
The next few bars would suggest (The bridge has begun by alternating tonic and subtonic.) we have moved to the;
plagal region (e-A7-D => ii-V7-I in D:). But, the subtonic;
colour of the verse has had us in the plagal corner since;
the song began.;
The band is very unsyncopated, suggesting (Starr simply taps the quarter notes during the 3/4 section.) this sudden;
timechange had them a little bluffed.;
??? Lennon introduces a new (2+2) four-bar idea. But, when he;
??? repeats it the first bar (e) is omitted.;
???;
??? e A7 A7 D;
??? (e) A7 A7 D |4;
???;
??? This clause ends a-d. After the second instance Lennon falls;
??? back into the verse 4/4 and a-e.;
? Lennon slides, glissando-like, up "right".;
return The change to 3/4 was hidden. The return to 4/4 is broadcast;
loud, driving the song back into the verse:;
o a-e;
o free drums;
o the complete verse tatoo;
This change literally propels the song. Lennon needs no further;
material in the song, the momementum is taken care of.;
verse;
bridge;
verse;
coda The body of the verse has the guitar echoing the parts of the;
vocal:;
Lennon turns this into a round for the coda/outro, repeating;
the last four bars.;
Lennon and Harrison double-track their parts.;
L-Vocal Round part 1, double tracked;
H-Vocal Round part 2, double tracked;
Organ pedal;
LG pedal plus doubles L-Vocal;
RG opening arpeggio;
Bass repeated quavers, pedal;
Drums 8/8 double time;
We now come to a new strategy, one (resolution) will be used frequently;
in his dramatic works. During the first three minutes of the song;
a pattern has been established which he now alters.;
The subtonic has the effect of undermining the tonic in the verse,creating conflict. Lennon resolves that conflict in the coda;
simply by harmonising the coda with the tonic alone. He does;
! need to alter the melody at all: it is squarely built around;
the tonic chord:;
.......;
In fact, the tonic prime is present thruout the verse:;
...;
Where the verse was stop/start, the outro pulses evenly.;
bridge strategy;
We can now understand why the bridge sticks with the verse area:;
anything else would have provided an escape from the verse;
conflict, thus lessening the affect of the coda resolution.;
The bridge is in fact ! much more than an extension of the verse;
pattern:;
Lennon still wants variety in the bridge: (A G A G A e=G A D A D)'s where the 3/4;
section comes in. The bridge varies the motion rather than the key.;
... birth of dramatic device (... more on bridge motion change ... compare with We Can Work triplets) carries him thru till White Album;
here ...;
difference between body odd-time and cadential odd-time.;
Melody;
Nursery-Rhyme simplicity -- like a classical theme;
Open fifth -- gurdys within;
Development in bridge;
Canon as outro;
.....;
A, A/g takes shape;
Melodic;
coda is a round;
Pedal-coda - A-G]* -> A-A*;
Open octaves -- Revolver sound;
Idioms;
This song invents idioms;
Fascinating to see the first signs of the A, A/g... style emerge here.;
Lucy, Prudence, Walrus are some of the later songs.;
Here we have A-G.., but the melody stays on A (giving G2).;
The bridge stays in key - alters r. and phrazing - prudence, ...;
The pedal-coda idiom emerges here;
Four in a bar beat in the bridge - used there to launch into 3/4.;
Critical development for all of Pepper, Walrus.;
All major chords, restricted pallette, recombinations;
Mixed time signatures - leans on We Can Work It Out, but harder to;
hear. Band is very tentative - they would get much freer on albums;
where they had more recording time.;
Exploring a chord, and a chord change;
The A-G also develops into multi-tonic works.;
Dr Robert comes close;
Other songs;
Getting Better -- the held pedal note;
Lucy -- decorated chord tune, beginning of Lucy here;
all the MajorChordSongs;
Title;
He Said He Said;
She Said She Said;
Reception;
Drumming;
Starr takes a great leap forward on this track. The fills;
sound fresh, and the tight damped 16th note fills became a;
signature during the following years.;
so phenomenal. We do (Ringo is ! given enough credit. The drumming on (...one of my favourite Beatle songs is She Said She Said...) song is) at sound checks;
and it's so much fun to play if you can pull it off.;
Billy Joel, SS16;
As a performance, She Said She Said, is the outstanding track;
with drumming technically finer than (on Revolver, emotionally tense... Whenever the feeling is real,Starr rises to the occasion, and here he holds the track together) of his other;
tour-de-force, Rain.;
!!! [Need the video quote from Starr, (RITH169) they were more adventurous;
on Lennon's tracks, because the songs were more adventurous];
Anecdotes;
Mixolydian;
Fonda;
'Found';
Composing tapes - know it was reworked;
Who's Who	;
Fonda had got hung up on an anecdote about an operation he had;
during which he almost died. He kept going on about what it was;
for(;;) {like to be dead ; if ( John couldn't take it anymore and barked,"Listen mate, shut up about that stuff.") break;}
TLYM187/188;
I wrote it after meeting Peter Fonda, who said he knew what;
it was like to be dead.;
Lennon CB83;
That's mine. It's a - an interesting track. The guitars are great on;
it. That was written after an acid trip in L.A. during a break in the;
Beatles' tour where we were having fun with the Byrds and lots of;
girls. Some from PLAYBOY, I believe. Peter Fonda came in when we were;
on acid and he kept coming up to me and sitting next to me and;
whispering, "I know what it's like to be dead.";
about (He was describing an acid trip he'd been on. We didn't want to hear)! We were on an acid trip and the sun was shining and the;
girls were dancing and the whole thing was beautiful and Sixties, and;
this guy - who I really didn't know; he hadn't made *Easy Rider or;
anything - kept coming over, wearing shades, saying, "I know what it's;
like to be dead,' and we kept leaving him because he was so boring!;
And I used it for the song, but I changed it to "she" instead of "he.";
It was scary. You know, a guy ... when you're flying high and;
(whispers) "I know what it's like to be dead, man." I remembered the;
incident. Don't tell me about it! I don't want to know what it's like;
to be dead!;
Lennon, DSL152;
Fonda came, and (...The second time we had it [LSD] was different... And Peter) was another thing, and he kept saying;
in a whisper 'I know what it's like to be dead' and we said;
'What?' and he kept saying it. We were saying 'For Christs sake;
What else turned into (going on about it. And (shut-up, we don't care, we don't want to know' and he kept)'s how I wrote "She said, she said,I know what it's like to be dead".) song?;
Well it was a sad song. It was just an acidy song, I suppose.;
"And when I was a little boy", you see... a lot of early;
childhood was coming out, anyway.;
How long did LSD go on?;
It went on for years. I must have had a thousand trips.;
Literally a thousand or a couple of hundred?;
Lots. I used to eat it all the time.;
LR76 Through what albums?;
I don't know. I never took it in the studio. Once I did, actually,I thought I was taking some uppers and I was ! in the state of;
handling it. And I can't remember what album it was [Lucy], but I;
took it and I just noticed ...;
if ( anywhere at all]) {[more here, but should be moved to Lucy, ;}
Lennon 1970, LR75/76;
The Beatles rented a house in Los Angeles in August 1965. They had;
a party, attended by Aspinall, Byrds McGuinn and Crosby,Peter Fonda and reporter Don Short.;
(...I remember sitting out on the deck of the house with George,who was telling me that he thought he was dying. I told him) there was nothing to be afraid of and that all he had to do;
was relax. I said I knew what it was like to be dead because when;
I was 10 years old I'd accidentally shot myself in the stomach;
while ( I was on the) {and my heart stopped beating three times ;}
operating table because I'd lost so much blood.;
John was passing at the time and heard me saying "I know what;
it's like to be dead". He looked at me and said, "You're making;
me feel like I've never been born. Who put all that shit in your;
head?";
...When I heard Revolver for the first time I knew exactly;
where the song had come from, although John never acknowledged it;
to me and I never mentioned it to anyone.;
Peter Fonda:?? in HDW111;
We were all on acid and John couldn't take it. John said, "Get;
this guy out of here". It was morbid and bizarre. We'd just;
finished watching Cat Ballou with Jane Fonda in it and John;
didn't want anything to do with the Fondas. He was holding the;
movie against Peter and what he said just added to it.;
I wrote the first thing (Roger McGuinn:?? in HDW111) came into my head and it was "When;
I was a boy", in a different beat. But it was real because it had;
just happened.;
Lennon:?? in HDW111;
Beethoven;
Harp quartet, first movement coda;
Composing Tapes;
Mar [1966]: John cut six demos of She Said She Said, tentatively;
titled He Said He Said.;
AM51 ...Lennon repeating the same phrase over and over again, to;
acoustic guitar accompaniment: "He said I know what it's like;
to be dead, he said". At this stage the line was taken at a;
register blues tempo, with Lennon picking Dylanesquely in the background.;
A couple of weeks later, Lennon had ...slowed the tempo down,substituting a chopping rhythm guitar for the finger-picked;
Who put all (original, and added some more lyrics--ad-libbing as he went along:) crap in your hair;
It's making me feel that my trousers are torn;
{I've felt your other mood recently: "Here I stand, head in hand";
in Hide Your Love Away and "When I was a boy, everything was right";
in She Said She Said};
see, when I wrote (Yeah, right. That was pure. That was what I meant all right. You) I had the "She said she said", but it was;
just meaning nothing. It was just vaguely to do with someone who;
had said something like he knew what it was like to be dead, and;
then it was just a sound.;
for days and days and so I wrote the first thing (And then I wanted a middle-eight. The beginning had been around) came into my;
head and it was "When I was a boy," in a different beat...;
Lennon, November 23, 1968 in BJY48;
Sessions;
Single nine hour session, rehearsing through 25 takes;
Three final takes,  sizeof(3) best;
band (RE-)Guitar (Lennon);
(LE-)Guitar (Harrison);
Bass (McCartney);
Drums (Starr);
The R-Guitar guitar strongly resembles one of Sgt Pepper parts.;
Lennon and Harrison appear to have been alone for the dubs.;
The distinctive lead guitar sound is achieved by double tracking;
the guitar, and occasionally doubling it with organ.;
dubs L-Vocal Lennon;
B-Vocal Lennon, Harrison;
Reduction mix vacated one channel;
Guitar (Harrison);
Organ Lennon;
...............;
Instrumentation;
Harrison predominant in harmony;
E-guitar;
Sitar;
Organ;
Hand-claps;
Cymbals;
Distinct parts for each player.;
In particular, the drummer has an essential role, and a contrapuntal;
role.;
She Said sketchs, and Beethoven;
She Said is a major vehicle for the comparison between;
Lennon and Beethoven -- just before Fields and Pepper.;
Shows us how Lennon worked at (One of the few composing tapes to survive from 1966.) time.;
He is searching for the opening notes of the song.;
He knows they will be chord tones.;
Obsessively, he tries every possibility.;
Just like Beethoven.;
!!! Need Beethoven example;
Bridge;
Lennon tells us (The evolution of the bridge can be partially reconstructed.) he had to search for bridge idea for;
a few days. Suddenly, he decided to sing the first thing;
to come into his head, which was "when I was a boy", "in a;
different beat".;
Lennon then wrote the three preceding bars of the bridge, to;
introduce the idea:;
She said, "you don't understand what I said",I said, "No no no, you're wrong [when I was a boy...]".;
He set the first clause to one of the discarded opening ideas;
for the verse.;
He added a single bar of G for the second clause, simultaneously;
switching to 3/4 for the following section.;
(old verse);
4/4 3/4;
A G A G 3;
(when I was...);
A e A7 3;
A7 D A7 3;
A7 D [A from verse] 2 11;
Origins;
R61 August 65, Peter Fonda;
o1 Begins with Dylan-style a-guitar picking, register, bluesy;
He said, I know what it's like to be dead, he said;
Its making me feel (Who put all (o2 slower, chopping rhythm guitar, adding) crap in your hair) my trousers are torn;
Lennon repeats the single line over and over again. He has a;
single phraze and a musical idea to go with it.;
On the second demo he has extended the music;
any words to fit the tune and chords.;
Lennon is reported doing much the same on Don't Let Me Down;
(repeating the verse line).;
Goes into a trance state, listening to the movement of the;
music. Emptying his mind. Feeling the direction of the music.;
Lennon does ! necessarily start at the beginning, or with;
the first verse lyric. He starts with a kernel idea, a mixture;
 break; case lyric:
and music.;
R57 "When I was a boy; everything was right";
"The song shifts tempo in a liberating burst of optimism as;
Lennon sings these lines (above), only to be sucked back into the;
fog as the verse takes control. It's a brilliant piece of;
revealing for (arranging, no doubt done instinctively, but none the less)";
if ( done on solo guitar, but this line had to be) {Instinctive ;}
defined for the others to learn.;
It's me double off-beats;
Lennons mixing of 3/4 and 4/4 at this time:;
We Can Work It 4/4 3/4 Lennons 3/4 bridge;
She Said 4/4 3/4;
Good Day 4/4 .. McCartney;
Fields 6/8;
Lucy 3/4 4/4 Maccas 4/4 chorus;
Kite 4/4 3/4;
Good Morning 4/4, 5/4, 3/4;
All You Need Is 4/4 3/4;
Happiness all of them;
Need to keep the discovery fresh -- ! just the final result;
Use rewrites;
The dramatic device;
What Lennon has invented is a dramatic tool (It is difficult to underestimate this little piece of logic.) he can use;
in a 3-minute piece. The idea is simple:;
o Resolve (o Base the body of the song on a conflict) conflict in the coda;
? More than just a fancy coda/outro;
? A principle rather than a cliche;
? The difference between a piece of cloth and a kite;
? Solves the problem of song writing for Lennon;
? Is exactly whats missing musically on Fantasy;
? Explains the banging drops on Milk;
... Exercise in motion -- bridge as contrary motion -- cf Mindgames et al;
Lennons device is demanding: it cannot be simply repeated. It;
requires a new solution for each work.;
trance;
simple case of pedal/release;
the void;
The Void;
All You Need Is Love;
Walrus;
Prudence;
Placement;
Not just an outro;
Something has to have happened;
Difficult to convert trivial song;
Chronology;
early what was possible;
hard days night moons;
sale/help experimentation;
rubber soul stories/lyrics;
revolver proto-forms;
pepper some by design, some by chance;
magic full form;
white subsumed, occasional (prudence), lighter (julia);
It would be a mistake to suppose (Lennon wasn't just writing codas	) Lennon was only interested;
in how his songs ended. No-one listens to a song just to see how;
it ends. This device is just another part of the vocabulary: it is;
The song as something (more difficult rather than more important.) develops/changes/happens;
Solving the Rubber Soul problem;
Getting away from AABABA..;
The recent future;
The tendency to explain anything a Beethoven does as genius and;
anything a Lennon does as coincidence must be addressed here.;
The proof is simple: all the remaining songs Lennon works on;
if( the trip to India exhibit this device in some form.)break; }
period are the strongest examples of (Even more convincing is that all the 'great' songs from this) device.;
o coda placement;
o coda present;
o coda develops song;
o coda different to song;
o song enhances coda;
Void coda 4 fundamental case;
Rain coda 4 proto-form;
Bird coda 2 plagal end;
Sleeping coda 2 outro;
Robert coda 2 supertonic end -- gave up;
She Said coda 5* prime;
Fields coda 5*;
Day coda 5* harmonic;
Kite coda 4 tonic search;
Lucy coda 3 rhythmic;
Good Morning coda 2;
All You Need coda 5* rhythmic;
You Know My variations;
Walrus coda 5* unique;
Baby coda 2;
Bulldog coda 3 riff development;
Universe coda 2;
Prudence coda 5* pedal;
With A Little;
Getting Better;
Leaving Home;
Paperback coda 2 tonic outro;
Rigby 4;
Here There 0 close;
Submarine 1 chorus outro;
Goodday Sunshine 4;
For No-One 1 interrupted close;
Gotta Get You coda 2 scat outro;
Penny Lane coda 4 bitonic resolution;
Sgt Pepper;
Fixing A Hole outro 2;
When I'm 64	none;
Rita coda 4 iv7 solo;
Fool coda 2 outro;
Mystery Tour coda ? hard days night;
Mother none 0;
Beethoven;
Sonata form;
The equivalent device for Beethoven was Sonata form which had;
been developed in the early 1800's. Hadyn and Mozart had;
provided the finishing touchs.;
Beethoven extended sonata form by strengthening the coda,expanding it to a full development.;
Later he tended to revert, as Lennon did.;
Variation form;
Another form available to Beethoven;
Strawberry Fields;
You Know My Name;
I Want You;
More random;
Not just a clever way of getting more punch for an outro.;
It's a new mindset, a new way of looking at a song.;
And it produces a new kind of song.;
Instead of a pretty piece of cloth, we have a kite (-- Instead of having a picture of a boat, we have a real boat,-- one that moves.) flies.;
Instead of drawing we have a three-dimensional model.;
All the relationships are changed. The start, middle, end of;
a piece are actively bound together.;
But...;
This is no magic formula guaranteeing success.;
Each song needs its static solution.;
More..;
The worst way to listen to a song is to 'wait' for the magic;
bit to come. You must have had the experience of you, or someone;
} else {, listen to this bit...;
Spending ten minutes listening to a symphonic movement just to;
hear the bit where the trumpets and drums start blaring..;
Reading a book just to see how it ends...;
This device should be seen more as giving a jelly-fish work;
a solid spine. It affects all areas of the songs construction.;
For example, without the outro, She Said's verse/bridge would;
tend to be seen as rambling.;
Lennons new way of working is to take a kernel idea and let it;
grow into a verse, chorus, bridge, coda, outro, etc as it will.;
He seeks the natural grain of the work.;
It is akin to the process an author goes thru when writing a;
have its static life, (book. The author wants the character to lift off the page and) he reports.;
Its ! just the loud ones;
Dramatic---can't use dramatic!!!!!!!!!!!;
Julia is built around the same principle.;
Lennon's not the only one;
But he is the topic of this book -- we are interested in his;
development;
But he is the topic of this book -- we are interested in his;
development. McCartney has his examples, some of the  sizeof(1) hits;
But, what separates Lennon from others is (can be examined in this way.) he is consistant.;
And the variety of solution. For him it is ! a hit and miss affair.;
/* header rimod - usual cusp includes */
#ifndef _RIDER_H_rimod
#define _RIDER_H_rimod 1
#include "m:\rid\rider.h"
#include "m:\rid\medef.h"
#include "m:\rid\stdef.h"
#include "m:\rid\fidef.h"
#include "m:\rid\imdef.h"
#include "m:\rid\mxdef.h"
#include "m:\rid\dbdef.h"
#endif
