.title	debugs
dbrev.=1

;	%build
;	goto 'p1'
;	macro:
;	macro	rfs:debugs/object:rfb:debugs
;	link:
;	r link
;	rfb:debugs.fea=/Q//
;	lib:featur,rfb:debugs,rfb:revers,lib:share,lib:shplib
;	//
;	featur:20000
;	
;	^C
;	goto end
;	if "'p1'" goto end
;	set error none
;	remove/feature debugs
;	copy rfb:debugs.fea sy:debugs.fea
;	install/feature debugs
;	set error error
;	end:
;	%end

.include "rfs:debug.mac"
.end
