.title	ccexi - cc_exi - exit program
.include "lib:crt.mac"
$jbdef
smini$

;	c$cexi points to the exit routine chain.
;	See ccsav.mac for data and rest of envelope
;
;	Exit routines should look like this:
;
;	m$yexi:	.word	0			; next exit routine
;
;	my$ini:	mov	c$cexi,m$yexi		; once-only code
;		mov	#my$exi,c$cexi		; chain us in
;
;	my$exi:	...
;		jmp	@m$yexi

code	cc_exi : (cod:int)

	stack	ret,cod
cc.exi::bisb	sp.cod(sp),j$bsev
	jmp	cc$exi

.end
