.title	emdon - em_emt/374/375 done routine
.include "lib:crt.mac"

;	em$don - done routine for direct RT-11 EMT calls
;
;	o  Return R0 value
;	o  Return 0/1 for failure/success
;
;	em_emt (&r0, emt)
;	em_374 (&r0, chn|cod, ...)
;	em_375 (&r0, chn|cod, ...)
;
;em.374::mov	4(sp),r0
;	emt	374
;	jmp	em$don

	stack	ret,r0
em$don::mov	r0,@sp.r0(sp)	; return R0 value
	mov	#1,r0		; #1 => success
	sbc	r0		; #0 => failure
30$:	return

.end
