.title	fidev - device/channel data
.include "lib:crt.mac"
fbdef$
$cidef
$didef
smini$
fidef$

ccdat$
fiValc::.word	0			; fudge for explicit enter size
f$iiob::.word	0, f$ispc, 0, 0		; i/o emt block
f$ispc::.blkw	4			; rad50 filespec
f$inew::.blkw	4			; rad50 new name for rename
					;
f$idst::.blkb	di.bbs			; .DSTAT area
f$icst::.blkb	ci.bbs			; .CSTAT area
ccstr$
f$iidv::.asciz	/W-Invalid device [%s]/


.end
