.title	fidel - delete file
.include "lib:crt.mac"
$emdef
smini$

ccstr$
f$idel:	.byte	emdel.,0
	.asciz	/Error deleting file [%s]/
cccod$

code	fi_del (spc:*char, msg:*char) int
code	fx_del (spc:*char, msg:*char, ext:*fiTopn) int

	stack	ret,p1,p2,p3
fx.del::mov	sp.p3(sp),r0
	br	fi$del
fi.del::mov	#f$iiob,r0
	fall	fi$del
local
  proc	fi$del
	p1	spc
	p2	msg
	p3	ext			; fx_del only
	call	fi$opr #f$bopr,spc(sp),msg(sp),#f$idel,r0
  end

.end
