.title	fimis - check file missing
.include "lib:crt.mac"
$emdef
smini$

ccstr$
mod:	.asciz	/r/
def:	.asciz	/E-File exists [%s]/
	.even
cccod$

code	fi_mis (spc:*char, msg:*char) int

  proc	fi.mis
	p1	spc
	p2	msg
	call	fi.opn	spc(sp),#mod,#0
	beqw	r0,10$			; missing is fine
	call	fi.clo	r0,#0		; file exists -- report that
	call	fi$rep	msg(sp),spc(sp),#def
	mov	#-1,r0			; and fail
10$:	inc	r0
  end

.end
