.title	firea - read file
.include "lib:crt.mac"
fbdef$
smini$

;	fi_rea (*F, buf, cnt) int 
;
;	fine	all read and dandy
;	fail	some error

  proc	fi.rea	<r2,r3,r4>
	p1	fil,r4
	p2	buf,r2
	p3	cnt,r3
	mov	cnt(sp),r3		; get the count
	beq	20$			; simple
10$:	call	fi$gch			; generic get
	beqw	r0,#EOF,30$		;
	movb	r0,(r2)+		; store it
	dec	r3			;
	bne	10$			;
20$:	mov	#1,r0			;
	br	40$			;
30$:	clr	r0			; failure
40$:	end

.end
