;???;;	fiung - unget is all wrong
.title	fiung - unget character
.include "lib:crt.mac"
fbdef$
smini$

;	unget (cha : char)	; standard C routine
;
;	RIDER/C supports a single unget character
;	Only calls that run through GETC() see the unget character

ungetc::
fi.ung::psh	r4
	stack	r4,ret,cha,fil
	mov	sp.fil(sp),r4

	mov	sp.cha(sp),fb.ung(r4)	; store the character
	bis	#^o100000,fb.ung(r4)	; flag unget in progress

	pop	r4
	return

.end
