.title	rtsav - save/restore registers
.include "lib:crt.mac"

;	untested


;	call	rt$sav
;	call	rt$ret

rt$sav::pshs	<r4, r3, r3, r1, r0>
	stack	r0, r1, r2, r3, r4, ret
	psh	sp.ret(sp)
	stack	ret, r0, r1, r2, r3, r4, r5
	mov	r5,sp.r5(sp)
	return

	stack	ret, r0, r1, r2, r3, r4, r5
rt$res::pop	r5
	stack	r0, r1, r2, r3, r4, r5
	pops	<r0, r1, r2, r3, r4>
	stack	r5
	psh	r5
	stack	ret,r5
	mov	2(sp),r5
	stack	ret,xxx
	psh	(sp)
	stack	ret
	return

.end
