.sbttl	RUST preface
.enabl	lc, gbl, mcl
.list	ttm
.library "lib:rust.mlb"
.mcall	spl, .print
ma$yea=2021
local
                                                                                                                                                                                                                                                                                                                                                                                                 