;	Fails--see SKS:TIWAI.R
.title	tiwai - timed wait
.include "lib:crt.mac"
$cndef
$emdef
$dsdef
$rmdef
fbdef$
smini$
ccdat$
l$otwt:	.byte	0,emTWT.
	.word	l$ohot
l$ohot:	.word	0
l$olot:	.word	

l$ogvl:	.byte	0,emGVL.
	.word	rm.cfg
cccod$

  proc	ti.wai	<r2>
	p1	hot
	p2	lot
	mov	#50.,r2
	mov	#l$ogvl,r0
	emt	^o375
	bpcw	#cn50h$,r0,10$
	mov	#60.,r2
10$:	mov	hot(sp),r0
	mov	lot(sp),r1
	div	r2,r0
	mov	r0,l$olot
	mov	hot(sp),r0
	clr	r1
	div	r2,r0
	mov	r0,l$ohot
	mov	#l$otwt,r0
	emt	^o375
  end

.end
