;***:	GKS:GKSNA - SNAIL algorithm to library
.title	gksna - snail
.include "lib:rust.mac"

;	This routine destroys the process space

gk.sna::
;	pshs	<r5,r4,r3,r2>
	.settop	#-1
	mov	r0,r5
	sub	#<e-a>*2,r5
	mov	#begin,r4
	mov	a,(r4)+		;put in the first
10$:	mov	b,(r4)+
	mov	b+2,(r4)+
	mov	b+4,(r4)+
	mov	c,(r4)+
	mov	c+2,(r4)+
	mov	c+4,(r4)+
	cmp	r4,r5
	blo	10$
	mov	d,(r4)
	br	begin
	
a:	br	b
b:	decb	r0
	bne	b
	br	d
c:	decb	r0
	bne	c
	br	a
d:	br	c
e:

begin:
.end
