.title	loop	
.include "dcs:dcl.mac"

;	RUST/XM loop commands
;
;	REPEAT	NEXT	LEAVE	UNTIL	END
;	
;	%build
;	macro	dcs:setdev	/object:dcb:setdev
;	%end
;
;	%date
;	<06-Aug-1988 03:32:48.49>
;	%edit
;	<18   >
;
;	%commands
;	REPEAT
;	NEXT	
;	LEAVE
;	UNTIL	
;	END
;	%end
;
;	A frame stack is used:
;
;		dp.sta		Start offset 
;		dp.end		End offset
;		dp.cnt		Repeat count
;
;	The repeat block is pushed terminated by ELP.
